INSERT INTO country (name, code_name) VALUES ('Australia', 'AU');
INSERT INTO country (name, code_name) VALUES ('Canada', 'CA');
INSERT INTO country (name, code_name) VALUES ('France', 'FR');
INSERT INTO country (name, code_name) VALUES ('Hong Kong', 'HK');
INSERT INTO country (name, code_name) VALUES ('Iceland', 'IC');
INSERT INTO country (name, code_name) VALUES ('Japan', 'JP');
INSERT INTO country (name, code_name) VALUES ('Nepal', 'NP');
INSERT INTO country (name, code_name) VALUES ('Russian Federation', 'RU');
INSERT INTO country (name, code_name) VALUES ('Sweden', 'SE');
INSERT INTO country (name, code_name) VALUES ('Switzerland', 'CH');
INSERT INTO country (name, code_name) VALUES ('United Kingdom', 'GB');
INSERT INTO country (name, code_name) VALUES ('United States', 'US');